<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>KinematicTrees.KtNode</AssemblyName>
    <RootNamespace>KinematicTrees.KtNode</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Google.FlatBuffers" Version="24.12.23" />
  </ItemGroup>
</Project>
